name: Update Trends

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install
        run: npm install axios xml2js
        
      - name: Generate
        run: node generate.js
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # This uploads the index.html we just generated

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
